# Generated by Django 4.2.3 on 2023-07-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
