# Generated by Django 4.2.3 on 2023-07-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_alter_reportcard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_report',
            field=models.DateField(auto_now_add=True),
        ),
    ]
