# Generated by Django 4.2.3 on 2023-07-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_alter_reportcard_date_of_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_report',
            field=models.DateField(auto_now_add=True),
        ),
    ]
